# Generated by Django 5.0.4 on 2024-05-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='latestnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('newsline', models.CharField(max_length=5000)),
                ('field', models.CharField(max_length=50)),
                ('newsdetails',models.TextField()),
            ],
        ),
    ]
    
