# Generated by Django 5.0.4 on 2024-05-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='activitiess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityname', models.CharField(max_length=5000)),
                ('activitydetails', models.TextField()),
                ('activityheading', models.TextField()),
                ('activityimg', models.ImageField(upload_to='img')),
            ],
        ),
    ]
    
