# Generated by Django 5.0.4 on 2024-05-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_activitiess'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestnews',
            name='activitydetails',
            field=models.TextField(default='NOTHING'),
        ),
        migrations.AddField(
            model_name='latestnews',
            name='activityheading',
            field=models.TextField(default='NOTHING'),
        ),
        migrations.AddField(
            model_name='latestnews',
            name='activityimg',
            field=models.ImageField(default='NOTHING', upload_to='img'),
        ),
        migrations.AddField(
            model_name='latestnews',
            name='activityname',
            field=models.CharField(default='NOTHING', max_length=5000),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='newsdetails',
            field=models.TextField(default='NOTHING'),
        ),
    ]
