# Generated by Django 5.0.4 on 2024-05-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_latestnews_activitydetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='weeklynews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wimg', models.ImageField(upload_to='img')),
                ('wnewsline', models.CharField(max_length=5000)),
                ('wfield', models.CharField(max_length=50)),
                ('wnewsdetails', models.TextField(default='NOTHING')),
            ],
        ),
    ]
