# Generated by Django 5.0.4 on 2024-05-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_latestnews_wfield_latestnews_wimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='field',
            field=models.CharField(default='NOTHING', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='img',
            field=models.ImageField(default='NOTHING', null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='newsline',
            field=models.CharField(default='NOTHING', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='wfield',
            field=models.CharField(default='NOTHING', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='wimg',
            field=models.ImageField(default='NOTHING', null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='wnewsline',
            field=models.CharField(default='NOTHING', max_length=5000, null=True),
        ),
    ]
