# Generated by Django 5.0.4 on 2024-05-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_alter_latestnews_field_alter_latestnews_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestnews',
            name='Breaking',
            field=models.BooleanField(default=False),
        ),
    ]
